drop database QLNHAHANG_NO_INDEX
-- Phân vùng theo ChiNhanh
CREATE PARTITION FUNCTION pf_ChiNhanh (TINYINT)
AS RANGE LEFT FOR VALUES (1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15);

-- Phân vùng theo ThoiGian
CREATE PARTITION FUNCTION pf_ThoiGian (DATE)
AS RANGE LEFT FOR VALUES (
    '2022-01-01', '2024-01-01', '2024-04-01', '2024-07-01', '2024-10-01', '2025-04-01'
);

-- Phân vùng theo KhuVuc
CREATE PARTITION FUNCTION pf_KhuVuc (TINYINT)
AS RANGE LEFT FOR VALUES (1, 2, 3, 4, 5, 6);

-- Phân vùng theo LoaiThe
CREATE PARTITION FUNCTION pf_LoaiThe (NVARCHAR(20))
AS RANGE LEFT FOR VALUES (N'Membership', N'Silver', N'Gold');

-- Tạo Partition Functions
CREATE PARTITION FUNCTION pf_ChiNhanh (TINYINT)
AS RANGE LEFT FOR VALUES (1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15);

CREATE PARTITION FUNCTION pf_ThoiGian (DATE)
AS RANGE LEFT FOR VALUES (
    '2022-01-01', '2024-01-01', '2024-04-01', '2024-07-01', '2024-10-01', '2025-04-01'
);

CREATE PARTITION FUNCTION pf_KhuVuc (TINYINT)
AS RANGE LEFT FOR VALUES (1, 2, 3, 4, 5, 6);

CREATE PARTITION FUNCTION pf_LoaiThe (NVARCHAR(20))
AS RANGE LEFT FOR VALUES (N'Membership', N'Silver', N'Gold');

-- Tạo Partition Schemes
CREATE PARTITION SCHEME ps_ChiNhanh
AS PARTITION pf_ChiNhanh ALL TO ([PRIMARY]);

CREATE PARTITION SCHEME ps_ThoiGian
AS PARTITION pf_ThoiGian ALL TO ([PRIMARY]);

CREATE PARTITION SCHEME ps_KhuVuc
AS PARTITION pf_KhuVuc ALL TO ([PRIMARY]);

CREATE PARTITION SCHEME ps_LoaiThe
AS PARTITION pf_LoaiThe ALL TO ([PRIMARY]);
-- Phân vùng theo MaChiNhanh
CREATE TABLE HoaDon (
    MaPhieu INT PRIMARY KEY,
    NgayLap DATETIME NOT NULL,
    TongTien INT NOT NULL,
    MaChiNhanh TINYINT NOT NULL
)
ON ps_ChiNhanh(MaChiNhanh);

-- Phân vùng theo ThoiGian
CREATE TABLE PhieuDatMon (
    MaPhieu INT IDENTITY(1,1) PRIMARY KEY,
    NgayLap DATETIME NOT NULL,
    NhanVienLap CHAR(6),
    MaSoBan TINYINT,
    SoDienThoai CHAR(10),
    MaChiNhanh TINYINT NOT NULL
)
ON ps_ThoiGian(NgayLap);